name: 'CI / Linux'

on:
  push:
    branches:
      - development
      - linux
      - 'linux-release-*'
    tags:
      - 'release-*.*.*-linux*'
      - 'release-*.*.*-test*'
  pull_request:
    branches:
      - linux
      - linux-vnext
      - 'linux-release-*'

permissions:
  contents: read

jobs:
  arm64:
    name: Ubuntu arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Package and test application in container
        uses: ./.github/actions/desktop-ubuntu-arm64-packaging
      - name: Upload output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-arm64-artifacts
          path: |
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.sha256
          retention-days: 5
          if-no-files-found: error
  amd64:
    name: Ubuntu x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Package and test application in container
        uses: ./.github/actions/desktop-ubuntu-amd64-packaging
      - name: Upload output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-amd64-artifacts
          path: |
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.sha256
          retention-days: 5
          if-no-files-found: error
